import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { PACKAGE_ROOT } from './helpers.js';

const REPO_ROOT = join(PACKAGE_ROOT, '..', '..');

/**
 * Regression guard for the DATA-01 file-scope.
 *
 * The ticket's "Does not touch" list names "root manifests, lockfiles, `tools/**`,
 * `.github/workflows/**` (`00-foundation`)". This ticket makes exactly **two** changes outside
 * `packages/database/**` and `docs/**`, both mechanical consequences of declaring the workspace's
 * first native dependency:
 *
 *  - `pnpm-lock.yaml`, regenerated by pnpm — the ticket already anticipates this ("adding a declared
 *    dependency regenerates `pnpm-lock.yaml` as a build artifact");
 *  - a single `allowBuilds: { better-sqlite3: false }` entry in `pnpm-workspace.yaml`, without which
 *    pnpm 11 exits `ERR_PNPM_IGNORED_BUILDS` and no install in this repository produces a working
 *    `packages/database`. See ADR 0002 consequence (vi), and the deviations note on this ticket.
 *
 * This file pins that boundary so a *third* root edit fails a test rather than depending on a
 * reviewer noticing it: `tools/tests/frozen-paths.test.mjs` lists none of these paths, so nothing
 * else in the repository catches them.
 *
 * If `00-foundation` would rather own the `allowBuilds` key, these expectations are the thing that
 * moves with it — deliberately, by the module that takes it.
 */

/** Top-level YAML keys of a flat, two-space-indented document. Enough for `pnpm-workspace.yaml`. */
function topLevelKeys(yaml: string): string[] {
  return yaml
    .split('\n')
    .filter((line) => /^[A-Za-z_][A-Za-z0-9_-]*\s*:/.test(line))
    .map((line) => line.slice(0, line.indexOf(':')).trim());
}

function repoText(relativePath: string): string {
  return readFileSync(join(REPO_ROOT, relativePath), 'utf8');
}

describe('DATA-01 file-scope (ticket "Does not touch": root manifests, tools/**)', () => {
  it('adds exactly one key to the root pnpm-workspace.yaml, and it is the build policy', () => {
    const workspace = repoText('pnpm-workspace.yaml');
    expect(topLevelKeys(workspace)).toEqual(['packages', 'allowBuilds']);
    // `false`, not `true`: better-sqlite3 13.x ships N-API prebuilds and declares no install script,
    // so denying the source build keeps a C++ toolchain off every machine's critical path. pnpm
    // writes the key as a `set this to true or false` stub on the failing install — a stub left
    // behind is a broken install, not a decision.
    expect(workspace).toMatch(/^ {2}better-sqlite3: false$/m);
    expect(workspace).not.toContain('set this to true or false');
  });

  it('adds no other dependency-build policy to any root manifest', () => {
    for (const key of [
      'allowBuilds',
      'onlyBuiltDependencies',
      'ignoredBuiltDependencies',
      'strict-dep-builds',
      'strictDepBuilds',
      'dangerouslyAllowAllBuilds',
    ]) {
      for (const path of ['package.json', '.npmrc']) {
        expect(repoText(path), `${path} carries ${key}, which DATA-01 does not own`).not.toContain(
          key,
        );
      }
      if (key === 'allowBuilds') continue;
      // Comments stripped: the file explains *why* `strictDepBuilds` forces the one key it does
      // carry, and a prose mention is not a setting.
      const settings = repoText('pnpm-workspace.yaml')
        .split('\n')
        .filter((line) => !line.trimStart().startsWith('#'))
        .join('\n');
      expect(
        settings,
        `pnpm-workspace.yaml carries ${key}, which DATA-01 does not own`,
      ).not.toContain(key);
    }
  });

  it('leaves the root package.json scripts and toolchain pins alone (ticket Non-goals)', () => {
    const root = JSON.parse(repoText('package.json')) as {
      scripts?: Record<string, string>;
      engines?: Record<string, string>;
      packageManager?: string;
      dependencies?: Record<string, string>;
    };
    // "No root package.json scripts. Root manifests are 00-foundation's."
    expect(Object.keys(root.scripts ?? {})).not.toContain('db:migrate');
    expect(root.dependencies).toBeUndefined();
    expect(root.engines?.['node']).toBe('24.18.0');
    expect(root.packageManager).toBe('pnpm@11.4.0');
  });

  it('leaves the tools/ workspace assertions to 00-foundation', () => {
    // DATA-01 must satisfy the repository-wide skeleton assertions, never relax them. The exact-pin
    // rule is the one this package's new dependencies are measured against; a rewrite that keeps the
    // title and drops the assertion is the violation this looks for.
    const skeleton = repoText('tools/tests/skeleton.test.mjs');
    expect(skeleton).toContain(
      "it('pins every member dependency to an exact version, with no range'",
    );
    expect(skeleton).toContain('EXACT_VERSION');
    expect(repoText('tools/workspace-assertions.mjs')).toContain('assertEntryFilesEmpty');
  });

  it('is not vacuous — the YAML key reader sees an appended block', () => {
    const tampered = "packages:\n  - 'packages/*'\nallowBuilds:\n  better-sqlite3: false\n";
    expect(topLevelKeys(tampered)).toEqual(['packages', 'allowBuilds']);
    expect(topLevelKeys("packages:\n  - 'packages/*'\n")).toEqual(['packages']);
  });
});
